config/routes.rb
Rails.application.routes.draw do
  root to: "organizations#index"

  resources :organizations, only: [:index, :show, :edit, :update]
  resources :eligibilities

end

app/models/eligibility.rb
class Eligibility < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true

  has_and_belongs_to_many :organizations
end

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :organization

  validates :address, :city, :state, :zipcode, presence: true
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  validates :description, presence: true

  has_many :locations
  has_and_belongs_to_many :eligibilities

  scope :by_eligibility, ->(eligibility) {  joins(:eligibilities).where(eligibilities: { name: eligibility }).uniq.order(:id) }

  def has_all_eligibilities(eligibilities)

    eligibilities.each do |ele|
      unless self.eligibilities.include?(ele)
        return false
      end
    end
    return true
  end

  def self.and_filter(eligibilities)
    if eligibilities.length == 1
      Organization.by_eligibility(eligibilities.first)
    elsif eligibilities.length > 1
      eligibilities_list = []
      has_all = []

      eligibilities.each do |ele|
        eligibility = Eligibility.find_by_name(ele)
        eligibilities_list << eligibility
      end

      Organization.by_eligibility(eligibilities).each do |org|
        if org.has_all_eligibilities(eligibilities_list)
          has_all << org
        end
      end

      has_all
    else
      raise ArgumentError.new("Must pass at least one eligibility")
    end
  end

  def self.filter(params)
    if params[:eligibilities]
      if params[:filter_type] == 'Accepts any'
        self.by_eligibility(params[:eligibilities]).includes(:locations)
      elsif params[:filter_type] == 'Accepts all'
        self.and_filter(params[:eligibilities])
      end
    else
      self.all.includes(:locations)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  def index
    @organizations = Organization.filter(params)
    @eligibilities = Eligibility.all
    @selected = params[:eligibilities]
  end

  def show
    @organization = Organization.find(params[:id]).decorate
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FullStackChallenge</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body>
    <div class="jumbotron jumbotron-fluid">
      <div class="container">
        <%= link_to "Resource Search", root_path, class: 'lead' %>
      </div>
    </div>
    <div class='container'>
      <div class="flashes">
        <% if flash[:success] %>
        <p class="flash--success"><%= flash[:success] %></p>
        <% end %>

        <% if flash[:alert] %>
        <p class="flash--alert"><%= alert %></p>
        <% end %>
      </div>

      <%= yield %>

    </div>
  </body>
</html>

app/views/organizations/_eligibilities.html.erb
<h3>Accepts:</h3>
<% if @organization.eligibilities.any? %>

  <ul id='resizing_list' class='list-group'>
    <% @organization.eligibilities.each do |eligibility| %>
        <li class='list-group-item darker-grey'><%= eligibility.name %></li>
    <% end %>
  </ul>
<% else %>
  <p class='darker-grey'>This organization has no eligibilities assigned to it.</p>
<% end %>

app/views/organizations/_filters.html.erb
<h4 class='darker-grey'>Filters</h4>
<%= form_tag organizations_path, method: 'get' do %>
<ul id='resizing_list' class='list-group'>
  <% @eligibilities.each do |eligibility| %>
    <li class='list-group-item grey-text responsive-list'>
      <p class = "no-margin">
        <% if @selected and @selected.include?(eligibility.name) %>
          <%= check_box_tag "eligibilities[]", eligibility.name, true  %>
        <% else %>
          <%= check_box_tag "eligibilities[]", eligibility.name  %>
        <% end %>
        <%= eligibility.name %>
      </p>
    </li>
    <br class='hidden-xs hidden-sm'>
  <% end %>
</ul>
<div class=''>
  <a class="" data-toggle="collapse" href="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
    Search Options
  </a>
  <div class="collapse" id="collapseExample">
    <div class="well">
      <%= radio_button_tag 'filter_type', 'Accepts any', true %>
      <%= label_tag 'accepts_any', "Find organizations that accept any of these ", id: 'accepts_any' %>
      <br>
      <%= radio_button_tag 'filter_type', 'Accepts all' %>
      <%= label_tag 'accepts_all', "Find organizations that accept all of these ", id: 'accepts_all' %>
    </div>
  </div>
  <%= submit_tag 'Apply filter', class: 'btn btn-primary float-right' %>
</div>
<br>
<% end %>

app/views/organizations/_locations.html.erb
<h3>Locations:</h3>
<ul class='list-group'>
  <% @organization.locations.each do |location| %>
      <li class='list-group-item darker-grey'>
        <%= location.decorate.address %>
      </li>
  <% end %>
</ul>

app/views/organizations/_organization.html.erb
<li class='list-group-item'>
  <h4>
    <%= link_to(organization.decorate.name, organization_path(organization)) %>
  </h4>
  <div class='hidden-xs'>
    <% organization.locations.each do |location| %>
    <p><%= location.decorate.address %></p>
    <% end %>
  </div>
</li>
<br class='hidden-xs hidden-sm'>

app/views/organizations/edit.html.erb
<h1>Editing Organization</h1>

<%= render 'form', organization: @organization %>

<br>

<%= link_to 'Back to organization', organization_path(@organization) %> |
<%= link_to 'View all Organizations', organizations_path(@stack) %>

app/views/organizations/index.html.erb
<% provide(:title, "All Organizations") %>
<div class='container'>
  <div class='row'>
    <div class="col-xs-12 col-sm-4">
      <%= render 'filters' %>
    </div>

    <div class='col-xs-12 col-sm-8'>
      <ul class='list-group'>
        <% if @organizations.any? %>
          <%= render @organizations %>
        <% else %>
          <h4>There are no organizations matching your search criteria.</h4>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/organizations/show.html.erb
<% provide(:title, @organization.name) %>

<div class='container'>
  <div class='row'>
    <div class='col-md-12'>
      <h1><%= @organization.name %></h1>
      <h5 class='darker-grey hidden-xs'><%= @organization.description %></h5>
    </div>
  </div>
  <div class='row'>
    <div class='col-sm-4'>
      <%= render 'eligibilities' %>
    </div>
    <div class='col-sm-8'>
      <%= render 'locations' %>
    </div>
  </div>
</div>
<hr>
<%= link_to "Home", organizations_path, class: 'btn btn-primary' %>